export const OTP_TTL_SECONDS = 300;
export const OTP_MAX_ATTEMPTS = 5;
export const RESET_TOKEN_TTL_SECONDS = 900;

export const AuthEventType = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  REFRESH: 'REFRESH',
  REFRESH_REUSE: 'REFRESH_REUSE',
  LOGOUT: 'LOGOUT',
  OTP_REQUEST: 'OTP_REQUEST',
  OTP_FAILURE: 'OTP_FAILURE',
  PASSWORD_SET: 'PASSWORD_SET',
  PASSWORD_RESET: 'PASSWORD_RESET',
} as const;
